### ISSUE TITLE
Create architecture diagrams

### ISSUE THREAD

**Issue by JamesMcSweeney** [JamesMcSweeney/CSC431#1]

**Comment by alex-claman** [comment]
![CpySeqDia_CpySequenceDiagram](https://user-images.githubusercontent.com/67563523/113339809-04cd2f80-92f9-11eb-8e65-a08db02ac0b7.png)
Here is the coronapyrus package sequence diagram!

**Comment by alex-claman** [comment]
![DiscSeqDia_DiscSeqDiag](https://user-images.githubusercontent.com/67563523/113343135-668f9880-92fd-11eb-9103-f01724f92194.png)
Here is the Discord bot/Slack app sequence diagram!
