### ISSUE TITLE
Structural Design

### ISSUE THREAD

**Issue by JamesMcSweeney** [JamesMcSweeney/CSC431#8]
<Identify all components and model them using class diagrams>

**Comment by noahfjaccard** [comment]
The following structural design chart is a breakdown of the components of the Coronapyrus package.
*insert structural design for coronapyrus*
(then you would caption the diagram)

This next structural design char is a breakdown of the components of the initialized bot itself, either on Discord or Slack.
*insert chart for bot*
(caption the diagram, talk about the help case, where the info is coming from case, what the commands are and what they return)
